# Generated by Django 3.1.2 on 2020-10-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20201012_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='eva.jpg', upload_to='gallery/'),
        ),
    ]
